### ISSUE TITLE
Revisiting user statistics

### ISSUE THREAD

**Issue by smlt** [crombird/meta#10]
### Some context

When author info statistics were added to Crom 1, I had to make various changes to better match user expectations:

- Admin pages and fragment pages should not count towards individual user totals.
- Component and theme pages *should* count towards the total rating, but since they're not as visible as other articles, they pull down the average rating. So, they should be excluded when calculating the average rating.
- Average rating calculation should be intuitive (i.e. mean), and not complex or obtuse, regardless of "fairness" (e.g. interquartile mean)

### Revisting assumptions

As Crom expands outside of the SCP wiki, these assumptions need to be revisited and updated so that they're more fair and more applicable to both the main wiki and other language wikis. All of the expectations mentioned above are mostly based on conventions rather than any hard rules, so it may end up being that I'll have to hard-code custom behaviors for certain known wikis. 

- Admin pages are not always tagged `admin` (some branches leave them untagged, while others give them a different name)
- Categorizing pages (e.g. `fragment:`, `component:`, `theme:`) is not universal across all wikis. Some wikis may allow "meta" pages to be published under the default category.

### What now?

For now, I will avoid ambiguity as much as possible for Crom 2. This means excluding the following:

- Pages tagged as `admin`
- Pages under the `fragment:` category

This ticket will stay open until I feel nobody has any complaints on how Crom's statistics work.

**Comment by ammongit** [comment]
Just a thought, you could have a static configuration file that lists wikis by name and has a series of standard customization options. Excluded categories, excluded tags, etc. Could also possibly be exposed in a separate public repo so people can make PRs/comments on it.

**Comment by lambda-fairy** [comment]
Personally, I don't care for the average at all—if I want to know how well-regarded an author or work is, I go to scpper and check the Wilson score instead.

I guess that means I don't really value assumption 3:

> Average rating calculation should be intuitive (i.e. mean), and not complex or obtuse, regardless of "fairness" (e.g. interquartile mean)

**Comment by lambda-fairy** [comment]
I should add that mainstream sites like Rotten Tomatoes use opaque percentage scores without complaint, so perhaps that third "expectation" isn't a big of a deal as we think?

**Comment by ammongit** [comment]
I agree, users don't need to need to fully understand the scoring algorithm to find it useful. Wilson score is a much more accurate measurement in an ups/downs system than what Wikidot uses. And since in the future it's likely we'll get neutralvotes (and scpper already has contributor rating), there's room for a thoughtful scoring system that provides an overview of readerbase reception.

**Comment by smlt** [comment]
Thanks for the input :)

Regarding tracking options per wiki, it seems like that's the best approach. I spent a while going through the many different non-English wikis and my general impression is that none of them are (and have never needed to be) standardized when it comes to URLs and page formatting. It still remains how much of that logic I can offload to declarative configuration files, and how much is actual JavaScript logic.

As Crom develops its own identity, it looks like I really need to do my research on what people want to see from the author info view. I'll leave this ticket open and add to it as I get around to this topic. And regarding opaque scores, people do complain about them (see [OpenCritic](https://www.pcgamer.com/opencritic-review-aggregator-launches-as-a-metacritic-alternative/)), but the use of something like a Scpper-style contributor score could also work.

I might consider throwing together a survey or something like that...

**Comment by ammongit** [comment]
One thing to consider is that a single authoritative score may not be ideal. There are different kinds of metrics people are interested in when it comes to "how much do people read this author", off the top of my head you have "total readership" (`ups + downs + neutral`) next to a balanced Wilson score, for instance.

**Comment by smlt** [comment]
There's no real end goal to this ticket, so I'm just going to close it. I appreciate the feedback!
