### ISSUE TITLE
Track parent pages

### ISSUE THREAD

**Issue by rossjrw** [crombird/meta#31]
It'd be pretty neat if Crom were able to track to which page a give page is parented, if any.

An application consuming the API would then be able to construct full parent-child relationships if it maintains a database of all articles, but if not, it might be useful to also expose for each page a list of pages that consider it their parent.

**Comment by smlt** [comment]
Done! `PageWikidotInfo` objects have `parent` and `children` properties now ([see example](https://bit.ly/3b1PDWX)). Additionally, you can also filter by complex parent/children relationships (e.g. pages with parents/children by a specific author or above a certain rating), but don't go overboard here; I haven't found a reason to add complexity limits to filters yet 😉.

Out of curiosity, do you have a specific reason for needing this data other than a "nice to have"? Maybe I can extract and present more helpful information in the API based on the relationship data.

**Comment by rossjrw** [comment]
Perfect - thank you!

> do you have a specific reason for needing this data?

My bot's stated goal, inasmuch as that means anything, is to be able to automate routine plugging on e.g. reddit. It'd be nice to be able to tag that plug with e.g "New Antimemetics Division Article" based on the parent page. That's pretty much it, for my use case.
