### ISSUE TITLE
RFC: Adding HISTORICAL_AUTHOR and HISTORICAL_REWRITE attribution types

### ISSUE THREAD

**Issue by smlt** [crombird/meta#32]
Currently, attributions have five types (`AUTHOR`, `REWRITE`, `TRANSLATOR`, `MAINTAINER`, and `SUBMITTER`) initially based on the EN wiki's attribution metadata types. An additional "submitter" type is provided as a convenience, and pulls in wikidot submitter info if no explicit attribution metadata is provided for a page.

However, this still has a few issues in that all authorships and rewrites are treated as equivalent attributions, when it could be argued that it isn't the case. It also muddies uses of page filters (e.g. `crom au`), where an author's "latest page" might actually be a rewrite of their page by another author. Adding additional `HISTORICAL_AUTHOR` and `HISTORICAL_REWRITE` types separates those concerns, so that a `REWRITE` attribution can automatically be turned into an `HISTORICAL_REWRITE` when a newer rewrite attribution is created.

To clarify these changes:

- `HISTORICAL_AUTHOR` is returned instead of `AUTHOR` when a `REWRITE` attribution is present.
- `HISTORICAL_REWRITE` is returned instead of `REWRITE` when a `REWRITE` attribution with a newer date is present.

This may cause issues if a single page's attribution metadata is split over multiple sources, but I don't see this ever being the case, so it should be a safe change to make. This may be a backward incompatible change depending on how these types are being used, so it can't be one of those overnight changes and might require some looking into.

---

This change is a prerequisite to hiding historical attributions in discord and reddit results.

**Comment by ammongit** [comment]
I don't have much to say on this issue, I think this makes sense as a way to distinguish rewrites from current authors.

For additional clarity, I would suggest that `AUTHOR` and `REWRITE` be renamed to `CURRENT_AUTHOR` and `CURRENT_REWRITE`:

So for any list of attribution on a page (I suppose other than the fallback "submitter" type?), there is always going to be one or more `CURRENT_AUTHOR`s, and zero or more `HISTORICAL_AUTHOR`s.

Similarly, if a page has been rewritten, there is going to be one or more `CURRENT_REWRITE`s, and zero or more `HISTORICAL_REWRITE`s.

**Comment by smlt** [comment]
That's a very good way of summarizing the behaviors of the new types!

> Similarly, if a page has been rewritten, there is going to be one or more CURRENT_REWRITEs, and zero or more HISTORICAL_REWRITEs.

As well as one or more `HISTORICAL_AUTHOR`s, which track(s) the initial author(s).

Thanks for the suggestion, that does clear up things for new API consumers. I'm going to consider renaming those attribution types, but that's going to cause a bit of a backward incompatibility issue with four other Crom services that depend on those names 😰

**Comment by smlt** [comment]
Closing! Found a much better alternative.
